### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by huguangcheng** [Ranking-VMR/TVR-Ranking#1]
你好你好，请问你这个是提了个新的子任务叫做，tvr-ranking吗？是根据本文查找最匹配的n个视频(时刻)？

**Comment by renjie-liang** [comment]
你好，感谢关注！
是的，我们提出了一个新的子任务，叫做Ranked VMR。同时我们重新标注了TVR数据集，叫做TVR-Ranking。
是的根据Query查找最匹配的n个时刻，同时还需要对这n个时刻排序。
我们认为这是更具有现实意义的任务，如果您想跟进这个任务，可以随时联系我，我会给您更多的帮助。
